### ISSUE TITLE
Images no longer exist

### ISSUE THREAD

**Issue by DBTDerpbox** [S-N00B-1/Xof#1]
![image](https://user-images.githubusercontent.com/65347035/208096605-cb1bf7a9-5b8d-4360-920a-1290d0af20ef.png)

Likely due to something causing the discord links in the html file to no longer exist, ive tried to open them manually but with no success

**Comment by S-N00B-1** [comment]
Resolved in [0cdcd35](https://github.com/S-N00B-1/Xof/commit/0cdcd355d9f9a2c47248396ca72813a7f663b2e3)
